### ISSUE TITLE
Complete the basic development

### ISSUE THREAD

**Issue by miek770** [miek770/nbreqs#2]
- [X] Review #1 .
- [x] Confirm if I should allow for more notebook versions (not sure what `nbformat.read(f, as_version=4)` entails).
- [x] Rename `main.py` to `nbreqs.py`.
- [x] Add to PyPI.
- [x] Ensure it can be installed with `pipx`.
- [x] Complete the README.md.
- [x] Add a LICENCE file (MIT).
- [x] Complete and cleanup the automated test.
- [x] Review relevant CLI arguments (ex.: `--pin` to pin dependencies (should be `False` by default).

**Comment by miek770** [comment]
`pipx` installs but then throws the following error; needs to be fixed:

```
> nbreqs --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\<username>\.local\bin\nbreqs.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'nbreqs.nbreqs'; 'nbreqs' is not a package
```

**Comment by miek770** [comment]
The `pipx` issue has been fixed; the `__init__.py` file was missing and I fixed the target in `pyproject.toml`.

**Comment by miek770** [comment]
For the simple purpose of extracting imports, `nbformat` should not convert the notebook's format. I'm going with:

```python
def process_notebook(nb: Path, pin: bool):
    with open(nb, "r", encoding="utf-8") as f:
        nb_content = nbformat.read(f, as_version=nbformat.NO_CONVERT)
```
